### PR TITLE
Add Docker environment to run OM

### PR DESCRIPTION
**Pull request by njwhite**
An easier way to get started!
    --------------------------------------------------------------------
    I, Nicholas White, being of legal age, certify, and take full responsibility for this
    certification, that I am authorized, without restriction
    of employer agreement or any other kind, to assign all rights to this 
    work (also known as "contribution"), and I do assign
    all rights to this work to Luke A. Call (all mentions of Luke A. Call here 
    also referring to his successors or assigns), who, by incorporating
    this work into the OneModel project, promises that this will promptly be 
    made publicly available under the license agreement
    under which the project is generally made available at that time, and also
    thereby grants back to me non-exclusive,
    royalty-free and non-cancellable rights to the work (i.e., this work, 
    changes or enhancements, not the program that they enhance), to do 
    as I see fit.  I understand that Luke A. Call may assign rights to other 
    entities or release this work under other
    licenses in the future, as seems to him best for the good of this project 
    and humankind as a whole.
    Any other future submissions or contributions by me of work to Luke A. Call 
    for use in the OneModel project will be under these same terms.  

    I may revoke this agreement by so stating in an email message (or 
    certified mail) to which I receive a reply or receipt, but 
    only with respect to work submitted after that time.  Luke A. Call 
    may revoke his participation in this agreement simply by removing 
    all such work or contribution in question from use by the OneModel project, 
    and/or by replacing it with other material.  After any revocation of this
    agreement, I will assert no related patent claims against the OneModel 
    project or Luke A. Call, even if similar code is subsequently added.

    Any legal contest around this agreement will be decided in and per the 
    laws of the State of Utah, or in a jurisdiction chosen at Luke
    A. Call's discretion.  If a court declares any part of this agreement 
    invalid or ineffective, the remaining parts may remain in force at Luke A.
    Call's discretion.  

    By incorporating the contribution Luke A. Call also agrees that: if he dies
    or becomes permanently incapacitated, and a new GNU AGPL is released by the
    Free Software Foundation, and neither he nor his successors or assigns 
    openly state his or their position on the new GNU AGPL within a year (in a 
    OneModel mailing list or similarly related and prominent forum), then the 
    project's source code will automatically fall under that new version 
    of the GNU AGPL, assuming it agrees in spirit with the GNU AGPL 
    version 3 from the Free Software Foundation.
--------------------------------------------------------------------

### CODE REVIEW

**Comment by lcall** [comment]
Am delighted to see your pull request.  

How was it tested? (both docker and db changes.

I'd enjoy hearing how you use OM, how you heard about it, and which docs were useful/not.

**Comment by njwhite** [comment]
Hi @lcall! I've added instructions for running the tests using maven, and `mvn test` now passes (I needed a few more changes, and had to force the timezone to MST in the `pom.xml`!). The integration tests don't quite work properly (`ERROR: Got an error looking for "OM db purge success.}.`)

It'd be great to have a longer conversion about the points you mentioned and some of the design choices you've made. Would email be better? Or the mailing list?

**Comment by lcall** [comment]
Sounds good; thanks.  I will review further in the coming days. I believe I had done (the equivalent of)  some of the db changes for the pg 10.x upgrade on the "wip" branch but meaning to read about its changes WRT schemas, before pushing, but haven't got to it yet.  The mailing list sounds good for design, how you heard of it, use, &c.

**Comment by onemodel** [comment]
Am clearing out a few things, and fixes for expect tests (mvn verify) to work again...maybe ~ 1/2 way to giving a better response here.

**Comment by onemodel** [comment]
Unable to log in as lcall at the moment for some reason, but:

   You have obviously done your prior homework--good job there, w/ 
   running/tweaking for tests, etc.
 
   I rebased & combined/merged & pushed your changes, with others of mine and some minor modifications to yours.
 
   You probably want to update your path per recent INSTALLING changes.  I 
   changed the Dockerfile for it, but you might want to check that.
 
   I had another commit already  with the DB changes: there were other lines that needed it, and it might be more readable if they are all written with the same even when w/ multi-columns (to me at least).  Ie, the "ROW(...)" syntax.
 
   The curly braces in "try" around an "if" line:  helps avoid future errs in 
   maintenance--i prefer when not on a single line.
 
   I got "mvn verify" running again but not sure if it does in docker.

   What was the java.net.ConnectException for?  It seems ok w/o.
 
   One change from multiline to single on some lines is because sometimes it helps me when reading, to see more code in a given vertical space.
 
   But if something is on multiple lines, braces seem to me to reduce the chance 
   of a future maintenance error.
 
   The s$ ... style of strings might be better scala style but it seems less 
   guessable by a java programmer with one hour of scala knowledge, and I would 
   much like the code to be guessable by someone from about any language background.
 
   Same w/ "map", even though it may be more concise & elegant: I don't want to get much into idiomatic scala or even idiomatically functional at this point.  I *might* be persuaded if more contributors all disagreed with me.
 
   An even easier way to set up would be if there were a sqlite class (embedded 
   database), parallel to the postgres class, which fully configured itself: 
   possible in the future.
 
2 other suggested changes:

   It might be good to comment in the docker file, like: "See mention of docker 
   in core/INSTALLING".
 
   Is the user.timezone change in the pom to make the *Attribute tests 
   pass? If so one of us should probably make the tests not depend on that, 
   instead.  

   If you plan to do that soon, let me know, or I'll put it on my list.  Might 
     be as good as anything to delete the "MST" from them, or something.
 
   Thanks much!

**Comment by onemodel** [comment]
@njwhite , I just realized that the copyright assignment statement is in the github comment, but not the git comment.  Could you re-send some commit, possibly making one or two of the changes suggested above, or simply with "git commit --allow-empty", that has that statement in the git commit itself?  

I finally did answer your email, but on the om-list.  Any feedback on my comments (here & there) is appreciated, and feedback on being easy to work with.  I know faster answers would help but can't always promise.  (ps I don't necessarily oppose OM using JavaScript just as you described, since I don't have a better idea and what you suggest definitely sounds like a good addition).  

Thanks!

(ps: how did you hear about OM?)

**Comment by onemodel** [comment]
(pps @njwhite : the "git commit --allow-empty", that has that statement in the git commit should be on a newly updated master branch, rebased if needed. Thanks!)

**Comment by onemodel** [comment]
Regarding the "the user.timezone change" request I made above: I see now that is in a test-only section of the pom, so my request didn't make sense (withdrawn..).  Thanks for the changes.

**Comment by lcall** [comment]
@njwhite : anything i said or say in future is definitely open to debate/discussion.  It's just that I have reasons for many plans, and would need reasons to drop a guideline I have had in mind.  Either way, thanks for this and all the best.

**Pull request merged**
